PREFIX strdf: <http://strdf.di.uoa.gr/ontology#>

select (strdf:distance(?g1, ?g2, <http://www.opengis.net/def/uom/OGC/1.0/degree>) as ?dist)
where
{
	<http://example.org/id/Point/5531> <http://example.org/ontology/hasGeometry> ?g1 .
	<http://example.org/id/Point/5532> <http://example.org/ontology/hasGeometry> ?g2 .
}