#!/bin/bash
#
# Script for running the main classes of Strabon. The main classes of Strabon comprises
# QueryOp, , UpdateOp, and StoreOp.
#
# Author: Charalampos (Babis) Nikolaou <charnik@di.uoa.gr>
#

# command name
CMD="$(basename ${0})"

# absolute directory name of this command
LOC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUNTIME="${LOC}/../runtime"

function help() {
	echo "Usage: ${CMD} [OPTIONS] COMMAND ARGS"
	echo
	echo "Interface to execute the main classes of Strabon, such as QueryOp, StoreOp, UpdateOp, etc."
	echo
	echo "	COMMAND	 : one of \`query', \`update', \`store', or \`help'"
	echo "	ARGS	 : arguments according to selected command"
	echo
	echo "OPTIONS can be any of the following"
	echo "	-d	 : don't run, just print what shall be executed"
	#echo "	-c FILE	 : configuration file to use for the connection. It defaults to \`${HOME}/.strabon'."
}

function help_query() {
	echo "Usage: ${CMD} query SPARQL_QUERY"
	echo
	echo "Execute a SPARQL query on Strabon."
	echo
	echo "	SPARQL_QUERY	: the SPARQL query to execute or an alias name such as the following:"
	echo "				size: returns the number of triples"
}

function help_update() {
	echo "Usage: ${CMD} update SPARQL_UPDATE"
	echo
	echo "Execute a SPARQL Update query on Strabon."
	echo
	echo "	SPARQL_UPDATE	: the SPARQL update query to execute or an alias name such as the"
	echo "			  the following:"
	echo "				clear: deletes all triples"
}

function help_store() {
	echo "Usage: ${CMD} store [OPTIONS] FILE..."
	echo
	echo "Store RDF documents in Strabon."
	echo
	echo "	FILE	: the file containing the RDF document to store. It can be a filename or a URL,"
	echo "		  (i.e., file:///tmp/file.nt, http://www.example.org/file.nt,"
	echo "		  ftp://www.example.org/file.nt, etc.)."
	echo 
	echo "OPTIONS can be one of the following"
	echo "	-f FORMAT : the RDF format of the files to store. The format can be one of the following:"
	echo "		    \`ntriples' (default), \`n3', \`rdfxml', or \`turtle'."
}

# runtime package
PKG="eu.earthobservatory.runtime"

# the underlying database to use (one of postgis or monetdb)
DATABASE="postgis"

# the main class to run
CLASS="QueryOp"

# the hostname at which the database runs
HOST="localhost"

# the port at which the database listens
PORT=5432

# the database name to connect to
DB="endpoint"
DB="strabon"

# the username for the database connection
DBUSER="charnik"

# the password for the database connection
DBPASS="charnik"

# the query to run
QUERY=

# the RDF format of the files to store (defaults to ntriples)
FORMAT=

# predefined queries
QUERY_SIZE="SELECT (COUNT(*) as ?C) WHERE {?s ?p ?o}"
QUERY_DELETEALL="DELETE {?s ?p ?o} WHERE {?s ?p ?o}"

# debug option for log4j configuration:
#-Dlog4j.debug
#-Dlog4j.configuration=\"${RUNTIME}/log4j.properties\"

# just print what shall be executed
DEBUG=0

# configuration file for the Strabon connection
STRABON_CONF="${HOME}/.strabon"

# read script options
case "${1}" in
	-d)
		shift
		DEBUG=1
		;;
	-c)
		shift
		if ! test $# -gt 1; then
			help
			exit 1
		fi
		STRABON_CONF="${1}"
		if ! test -e "${STRABON_CONF}"; then
			echo "${CMD}: configuration file \"${1}\" does not exist."
			exit 1
		fi
		shift
		;;
esac

# determine command to execute
case "${1}" in
	help)
		shift
		if test $# -ge 1; then
			case "${1}" in
				query)
					help_query
					;;
				update)
					help_update
					;;
				store)
					help_store
					;;
				*)
					help
					;;
			esac
			exit 1
		fi
		help
		exit 0
		;;
	query)
		CLASS="QueryOp"
		shift
		if ! test $# -eq 1; then
			help_query
			exit 1
		fi
		QUERY="${1}"

		# check for predefined queries
		case "${QUERY}" in
			size)
				QUERY="${QUERY_SIZE}"
				;;
		esac
		;;
	update)
		CLASS="UpdateOp"
		shift
		if ! test $# -eq 1; then
			help_update
			exit 1
		fi
		QUERY="${1}"

		# check for predefined queries
		case "${QUERY}" in
			clear)
				QUERY="${QUERY_DELETEALL}"
				;;
		esac
		;;
	store)
		CLASS="StoreOp"
		shift
		if ! test $# -ge 1; then
			help_store
			exit 1
		fi
		# check whether format is specified
		if test "${1}" = "-f"; then
			shift
			if ! test $# -ge 1; then
				echo "${CMD}: Option -f requires an RDF format (\`ntriples', \`n3', \`rdfxml', or \`turtle')."
				exit 2
			else
				FORMAT="${1}"
				case "${FORMAT}" in
					ntriples|n3|rdfxml|turtle)
						shift
						;;
					*)
						echo "${CMD}: invalid RDF format \"${FORMAT}\"."
						echo "${CMD}: valid RDF formats are \`ntriples', \`n3', \`rdfxml', or \`turtle'."
						exit 2
						;;
				esac
			fi
		fi
		# if no files are given
		if ! test $# -ge 1; then
			help_store
			exit 1
		fi
		# do not make an assignment of the files to QUERY
		# handle the case of storing multiple files afterwards
		# QUERY="${@}"
		;;
	*) 
		help
		echo
		echo "${CMD}: unknown command \"${1}\"."
		exit 1
		;;
esac

# compile command to execute
if test "${CLASS}" = "StoreOp"; then
	STRABON_EXEC=
	for file in "${@}"; do
		STRABON_EXEC="${STRABON_EXEC}(cd ${RUNTIME} && java -cp ./target/\*:. ${PKG}.${DATABASE}.${CLASS} ${HOST} ${PORT} ${DB} ${DBUSER} ${DBPASS} \"${file}\" ${FORMAT});
"
	done
else
	STRABON_EXEC="(cd ${RUNTIME} && java -cp ./target/\*:. ${PKG}.${DATABASE}.${CLASS} ${HOST} ${PORT} ${DB} ${DBUSER} ${DBPASS} \"${QUERY}\")"
fi

# execute command or debug
if test ${DEBUG} -eq 1; then
	echo "${CMD}: Debug is ON"
	echo "${CMD}: Printing command for execution"	
	echo "${STRABON_EXEC}"
else
	eval ${STRABON_EXEC}
fi
