#!/bin/bash
#
# Script for running the main classes of Strabon. The main classes of Strabon comprises
# QueryOp, StoreOp, etc.
#
# Author: Charalampos (Babis) Nikolaou <charnik@di.uoa.gr>
#

# absolute directory name of this command
LOC="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RUNTIME="${LOC}/../runtime"

function help() {
	echo "Usage: `basename ${0}` [OPTIONS] COMMAND ARGS"
	echo
	echo "Interface to execute the main classes of Strabon, such as QueryOp, StoreOp, UpdateOp, etc."
	echo
	echo "	COMMAND	 : one of \`query', \`update', \`store', or \`help'"
	echo "	ARGS	 : arguments according to selected command"
	echo 
#	echo "OPTIONS can be any of the following"
#	echo "	-d	 : don't run, just print what shall be executed"
}

# runtime package
PKG="eu.earthobservatory.runtime"

# the underlying database to use (one of postgis or monetdb)
DATABASE="postgis"

# the main class to run
CLASS="QueryOp"

# the hostname at which the database runs
HOST="localhost"

# the port at which the database listens
PORT=5432

# the database name to connect to
DB="endpoint"

# the username for the database connection
DBUSER="charnik"

# the password for the database connection
DBPASS="charnik"

# the query to run
QUERY=

# predefined queries
QUERY_SIZE="SELECT (COUNT(*) as ?C) WHERE {?s ?p ?o}"
QUERY_DELETEALL="DELETE {?s ?p ?o} WHERE {?s ?p ?o}"

# debug option for log4j configuration:
#-Dlog4j.debug
#-Dlog4j.configuration=\"${RUNTIME}/log4j.properties\"

DEBUG=0
#case "${1}" in
#	-d)
#		shift
#		DEBUG=1
#		;;
#esac

case "${1}" in
	help)
		shift
		if test $# -eq 1; then
			case "${1}" in
				query)
					help_query
					;;
				update)
					help_update
					;;
				store)
					help_store
					;;
				*)
					help
					;;
			esac
			exit 1
		fi
		help
		exit 0
		;;
	query)
		CLASS="QueryOp"
		shift
		if ! test $# -eq 1; then
			#help_query
			help
			exit 1
		fi
		QUERY="${1}"

		# check for predefined queries
		case "${QUERY}" in
			size)
				QUERY="${QUERY_SIZE}"
				;;
		esac
		;;
	update)
		CLASS="UpdateOp"
		shift
		if ! test $# -eq 1; then
			#help_query
			help
			exit 1
		fi
		QUERY="${1}"

		# check for predefined queries
		case "${QUERY}" in
			clear)
				QUERY="${QUERY_DELETEALL}"
				;;
		esac
		;;
	store)
		CLASS="StoreOp"
		shift
		if ! test $# -eq 1; then
			#help_query
			help
			exit 1
		fi
		QUERY="${1}"
		;;
	*) 
		help
		echo
		echo "ERROR: Unknown command \"${1}\"."
		exit 1
		;;
esac

CMD="(cd ${RUNTIME} && java -cp ./target/\*:. ${PKG}.${DATABASE}.${CLASS} ${HOST} ${PORT} ${DB} ${DBUSER} ${DBPASS} \"${QUERY}\")"

# execute or debug
if test ${DEBUG} -eq 1; then
	echo "`basename ${0}`: Debug is ON"
	echo "`basename ${0}`: Printing command for execution"	
	echo "	${CMD}"
else
	eval ${CMD}
fi

