PREFIX strdf: <http://strdf.di.uoa.gr/ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 
PREFIX noa: <http://teleios.di.uoa.gr/ontologies/noaOntology.owl#> 

SELECT distinct ?x1 ?x2 
			WHERE { 
				?x1 ?y1 ?z1 ?t1 .
				?x2 ?y2 ?z2 ?t2 .
				FILTER(strdf:meets(?t1, ?t2) && str(?x1) < str(?x2)).}